//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpedicionInternaPC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Basic")]
        public string Look {
            get {
                return ((string)(this["Look"]));
            }
            set {
                this["Look"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string UsuarioRecordar {
            get {
                return ((string)(this["UsuarioRecordar"]));
            }
            set {
                this["UsuarioRecordar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string UsuarioIdCliente {
            get {
                return ((string)(this["UsuarioIdCliente"]));
            }
            set {
                this["UsuarioIdCliente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string UsuarioModoValidacion {
            get {
                return ((string)(this["UsuarioModoValidacion"]));
            }
            set {
                this["UsuarioModoValidacion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsuarioCodigo {
            get {
                return ((string)(this["UsuarioCodigo"]));
            }
            set {
                this["UsuarioCodigo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsuarioPassword {
            get {
                return ((string)(this["UsuarioPassword"]));
            }
            set {
                this["UsuarioPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ExistePDA {
            get {
                return ((string)(this["ExistePDA"]));
            }
            set {
                this["ExistePDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool grvLote_colLote_Visible {
            get {
                return ((bool)(this["grvLote_colLote_Visible"]));
            }
            set {
                this["grvLote_colLote_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RutaImpresoraZebra {
            get {
                return ((string)(this["RutaImpresoraZebra"]));
            }
            set {
                this["RutaImpresoraZebra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ExisteDPM {
            get {
                return ((string)(this["ExisteDPM"]));
            }
            set {
                this["ExisteDPM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public byte TamAutogenerado {
            get {
                return ((byte)(this["TamAutogenerado"]));
            }
            set {
                this["TamAutogenerado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string TamCodAgencia {
            get {
                return ((string)(this["TamCodAgencia"]));
            }
            set {
                this["TamCodAgencia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AgenciaWS.asmx/")]
        public string AgenciaWS {
            get {
                return ((string)(this["AgenciaWS"]));
            }
            set {
                this["AgenciaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CampoDigitalizacionWS.asmx/")]
        public string CampoDigitalizacionWS {
            get {
                return ((string)(this["CampoDigitalizacionWS"]));
            }
            set {
                this["CampoDigitalizacionWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CampoExternoWS.asmx/")]
        public string CampoExternoWS {
            get {
                return ((string)(this["CampoExternoWS"]));
            }
            set {
                this["CampoExternoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CampoTipoDocumentoWS.asmx/")]
        public string CampoTipoDocumentoWS {
            get {
                return ((string)(this["CampoTipoDocumentoWS"]));
            }
            set {
                this["CampoTipoDocumentoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CasillaWS.asmx/")]
        public string CasillaWS {
            get {
                return ((string)(this["CasillaWS"]));
            }
            set {
                this["CasillaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ColaboradorWS.asmx/")]
        public string ColaboradorWS {
            get {
                return ((string)(this["ColaboradorWS"]));
            }
            set {
                this["ColaboradorWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConfiguracionWS.asmx/")]
        public string ConfiguracionWS {
            get {
                return ((string)(this["ConfiguracionWS"]));
            }
            set {
                this["ConfiguracionWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CuboWS.asmx/")]
        public string CuboWS {
            get {
                return ((string)(this["CuboWS"]));
            }
            set {
                this["CuboWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DocumentoExternoCargaWS.asmx/")]
        public string DocumentoExternoCargaWS {
            get {
                return ((string)(this["DocumentoExternoCargaWS"]));
            }
            set {
                this["DocumentoExternoCargaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DocumentoWS.asmx/")]
        public string DocumentoWS {
            get {
                return ((string)(this["DocumentoWS"]));
            }
            set {
                this["DocumentoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EntregaWS.asmx/")]
        public string EntregaWS {
            get {
                return ((string)(this["EntregaWS"]));
            }
            set {
                this["EntregaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EstadoVerificacionWS.asmx/")]
        public string EstadoVerificacionWS {
            get {
                return ((string)(this["EstadoVerificacionWS"]));
            }
            set {
                this["EstadoVerificacionWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExpedicionWS.asmx/")]
        public string ExpedicionWS {
            get {
                return ((string)(this["ExpedicionWS"]));
            }
            set {
                this["ExpedicionWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FeriadoWS.asmx/")]
        public string FeriadoWS {
            get {
                return ((string)(this["FeriadoWS"]));
            }
            set {
                this["FeriadoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeoWS.asmx/")]
        public string GeoWS {
            get {
                return ((string)(this["GeoWS"]));
            }
            set {
                this["GeoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IndicadoresWS.asmx/")]
        public string IndicadoresWS {
            get {
                return ((string)(this["IndicadoresWS"]));
            }
            set {
                this["IndicadoresWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MensajeriaWS.asmx/")]
        public string MensajeriaWS {
            get {
                return ((string)(this["MensajeriaWS"]));
            }
            set {
                this["MensajeriaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ModuloCreacionWS.asmx/")]
        public string ModuloCreacionWS {
            get {
                return ((string)(this["ModuloCreacionWS"]));
            }
            set {
                this["ModuloCreacionWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MonedaWS.asmx/")]
        public string MonedaWS {
            get {
                return ((string)(this["MonedaWS"]));
            }
            set {
                this["MonedaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MotivoCambioEstadoWS.asmx/")]
        public string MotivoCambioEstadoWS {
            get {
                return ((string)(this["MotivoCambioEstadoWS"]));
            }
            set {
                this["MotivoCambioEstadoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ObjetoWS.asmx/")]
        public string ObjetoWS {
            get {
                return ((string)(this["ObjetoWS"]));
            }
            set {
                this["ObjetoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OperarioWS.asmx/")]
        public string OperarioWS {
            get {
                return ((string)(this["OperarioWS"]));
            }
            set {
                this["OperarioWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PalomarWS.asmx/")]
        public string PalomarWS {
            get {
                return ((string)(this["PalomarWS"]));
            }
            set {
                this["PalomarWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PlantillaGeneralWS.asmx/")]
        public string PlantillaGeneralWS {
            get {
                return ((string)(this["PlantillaGeneralWS"]));
            }
            set {
                this["PlantillaGeneralWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PlantillaWS.asmx/")]
        public string PlantillaWS {
            get {
                return ((string)(this["PlantillaWS"]));
            }
            set {
                this["PlantillaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReclamoWS.asmx/")]
        public string ReclamoWS {
            get {
                return ((string)(this["ReclamoWS"]));
            }
            set {
                this["ReclamoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SeguridadWS.asmx/")]
        public string SeguridadWS {
            get {
                return ((string)(this["SeguridadWS"]));
            }
            set {
                this["SeguridadWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ServicioWS.asmx/")]
        public string ServicioWS {
            get {
                return ((string)(this["ServicioWS"]));
            }
            set {
                this["ServicioWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SIMServerWS.asmx/")]
        public string SIMServerWS {
            get {
                return ((string)(this["SIMServerWS"]));
            }
            set {
                this["SIMServerWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoCorrespondenciaWS.asmx/")]
        public string TipoCorrespondenciaWS {
            get {
                return ((string)(this["TipoCorrespondenciaWS"]));
            }
            set {
                this["TipoCorrespondenciaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoDocumentoExternoWS.asmx/")]
        public string TipoDocumentoExternoWS {
            get {
                return ((string)(this["TipoDocumentoExternoWS"]));
            }
            set {
                this["TipoDocumentoExternoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoDocumentoWS.asmx/")]
        public string TipoDocumentoWS {
            get {
                return ((string)(this["TipoDocumentoWS"]));
            }
            set {
                this["TipoDocumentoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoExpedicionWS.asmx/")]
        public string TipoExpedicionWS {
            get {
                return ((string)(this["TipoExpedicionWS"]));
            }
            set {
                this["TipoExpedicionWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoFeriadoWS.asmx/")]
        public string TipoFeriadoWS {
            get {
                return ((string)(this["TipoFeriadoWS"]));
            }
            set {
                this["TipoFeriadoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoReclamoUTDWS.asmx/")]
        public string TipoReclamoUTDWS {
            get {
                return ((string)(this["TipoReclamoUTDWS"]));
            }
            set {
                this["TipoReclamoUTDWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoResponsableWS.asmx/")]
        public string TipoResponsableWS {
            get {
                return ((string)(this["TipoResponsableWS"]));
            }
            set {
                this["TipoResponsableWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoUsuarioWS.asmx/")]
        public string TipoUsuarioWS {
            get {
                return ((string)(this["TipoUsuarioWS"]));
            }
            set {
                this["TipoUsuarioWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TurnoWS.asmx/")]
        public string TurnoWS {
            get {
                return ((string)(this["TurnoWS"]));
            }
            set {
                this["TurnoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UsuarioFacWS.asmx/")]
        public string UsuarioFacWS {
            get {
                return ((string)(this["UsuarioFacWS"]));
            }
            set {
                this["UsuarioFacWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UsuarioWS.asmx/")]
        public string UsuarioWS {
            get {
                return ((string)(this["UsuarioWS"]));
            }
            set {
                this["UsuarioWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PublicWS.asmx/")]
        public string PublicWS {
            get {
                return ((string)(this["PublicWS"]));
            }
            set {
                this["PublicWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auth.asmx/")]
        public string AuthWS {
            get {
                return ((string)(this["AuthWS"]));
            }
            set {
                this["AuthWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PF_Todo.asmx/")]
        public string PF_TodoWS {
            get {
                return ((string)(this["PF_TodoWS"]));
            }
            set {
                this["PF_TodoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RegistroWS.asmx/")]
        public string RegistroWS {
            get {
                return ((string)(this["RegistroWS"]));
            }
            set {
                this["RegistroWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReporteWS.asmx/")]
        public string ReporteRVAWS {
            get {
                return ((string)(this["ReporteRVAWS"]));
            }
            set {
                this["ReporteRVAWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IndicadorANSWS.asmx/")]
        public string IndicadorANSWS {
            get {
                return ((string)(this["IndicadorANSWS"]));
            }
            set {
                this["IndicadorANSWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoReclamoJefeWS.asmx/")]
        public string TipoReclamoJefeWS {
            get {
                return ((string)(this["TipoReclamoJefeWS"]));
            }
            set {
                this["TipoReclamoJefeWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportePeriodoWS.asmx/")]
        public string ReportePeriodoWS {
            get {
                return ((string)(this["ReportePeriodoWS"]));
            }
            set {
                this["ReportePeriodoWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TipoReclamoUsuarioWS.asmx/")]
        public string TipoReclamoUsuarioWS {
            get {
                return ((string)(this["TipoReclamoUsuarioWS"]));
            }
            set {
                this["TipoReclamoUsuarioWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SeguridadAzureWS.asmx/")]
        public string SeguridadAzureWS {
            get {
                return ((string)(this["SeguridadAzureWS"]));
            }
            set {
                this["SeguridadAzureWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ExisteDMA {
            get {
                return ((string)(this["ExisteDMA"]));
            }
            set {
                this["ExisteDMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string PageSize {
            get {
                return ((string)(this["PageSize"]));
            }
            set {
                this["PageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AsistenciaWS.asmx/")]
        public string AsistenciaWS {
            get {
                return ((string)(this["AsistenciaWS"]));
            }
            set {
                this["AsistenciaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RecorridoPisosWS.asmx/")]
        public string RecorridoPisosWS {
            get {
                return ((string)(this["RecorridoPisosWS"]));
            }
            set {
                this["RecorridoPisosWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57b3789e-9a55-4324-b028-f4460c70f468")]
        public string ClientId {
            get {
                return ((string)(this["ClientId"]));
            }
            set {
                this["ClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f26a3bc4-1409-43a2-ac2f-34ec8395d7ec")]
        public string Tenant {
            get {
                return ((string)(this["Tenant"]));
            }
            set {
                this["Tenant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api://57b3789e-9a55-4324-b028-f4460c70f468/user_impersonation")]
        public string scopes {
            get {
                return ((string)(this["scopes"]));
            }
            set {
                this["scopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string MinutosInactivo {
            get {
                return ((string)(this["MinutosInactivo"]));
            }
            set {
                this["MinutosInactivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Basic")]
        public string ApplicationThemeName {
            get {
                return ((string)(this["ApplicationThemeName"]));
            }
            set {
                this["ApplicationThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44342/ws/")]
        public string rutaWS {
            get {
                return ((string)(this["rutaWS"]));
            }
            set {
                this["rutaWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string autoajuste {
            get {
                return ((string)(this["autoajuste"]));
            }
            set {
                this["autoajuste"] = value;
            }
        }
    }
}
